# Generated by Django 4.1.2 on 2022-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='folowers',
            field=models.IntegerField(default=0),
        ),
    ]
