# Generated by Django 4.1.2 on 2023-02-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_likedpost_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedpost',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
