# Generated by Django 4.1.2 on 2023-02-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_likedpost_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedpost',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
